// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yezjxwahexsfbvhfxsji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inllemp4d2FoZXhzZmJ2aGZ4c2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTIyOTAsImV4cCI6MjA2ODI2ODI5MH0.8DH3ggR-jbKVRfZhHfHltk1TPCt30e4eqB4zw2l6w3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with options to disable real-time features to prevent WebSocket errors
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'X-Client-Info': 'webdaw-app'
    }
  }
  // Omitting the realtime property entirely to disable real-time features
});